name: Push To Windows VM

# Controls when the workflow will run
on:
  # Triggers the workflow on push request event for the master branch
  push:    
    branches: [main]

jobs:
  deploy:
    # Our previously created self-hosted runner
    runs-on: self-hosted
    
    # A sequence of tasks that will execute as part of the job
    steps:
      # Checks out repository so our job can access it
      - uses: actions/checkout@v2
      #Builds ClickOnce File Using PowerShell on the VM.
      - name: Power Shell Build     
        run: powershell msbuild /t:publish /p:PublishProfile=C:\actions-runner\_work\DeployToWindowsVMCO\DeployToWindowsVMCO\Properties\PublishProfiles\ClickOnceProfile.pubxml /p:PublishDir="C:\ClickOncePublish"
